### PR TITLE
Updating Eslint and Input Default Text

### PR DESCRIPTION
**Pull request by FranDelaCasa**
In this PR we add a new component prop: value.

This value is the default value that must appear in the input type text.

### CODE REVIEW

**Comment by FranDelaCasa** [comment]
@danderu @carlosvillu @davecarter @kikoruiz @ruben-martin-lozano please, review

**Comment by kikoruiz** [comment]
:+1: 

@FranDelaCasa please, let me know when this component is merged to master and published to npm with the new release because I'm with this task https://jira.scmspain.com/browse/SCMI-4786 and I'll need to add a new more release.

**Comment by FranDelaCasa** [comment]
Ok, I'll do.

**Comment by delacruz-dev** [comment]
:+1:

**Pull request merged**
